smiles_col: 'SMILES'
dose_col: 'CT_Dose'
route_col: 'DoseRoute'
time_cols_prefix: 'CT_TIME'
conc_cols_prefix: 'CT_CON'
save_path: './save_dir'
k: 5
num_epochs: 100
batch_size: 64
learning_rate: 1e-4
eps: 1e-6
warmup_ratio: 0.03
loss_fn: 'log_mae_time_exp_decay'
pretrain: 'mol_pre_all_h_220816.pt'
num_cmpts: 3
route: 'p.o.'
method: 'NeuralODE'
train_filepath: '/fs_mol/cuiyaning/user/uni-qsar/0821/optuna-dml/test_pk/data/CT_iv_train_val_50.csv'