smiles_col: 'SMILES'
dose_col: 'CT_Dose'
route_col: 'DoseRoute'
time_cols_prefix: 'CT_TIME'
conc_cols_prefix: 'CT_CON'
save_path: '/vepfs/fs_ckps/cuiyaning/pk/pair_model'
num_epochs: 1000
batch_size: 16
learning_rate: 1e-4
eps: 1e-6
warmup_ratio: 0.03
loss_fn: 'log_mae_time_decay'
pretrain: 'mol_pre_all_h_220816.pt'
num_cmpts: 3
route: 'p.o.'
method: 'NeuralODE'
# pair_data_path: '/vepfs/fs_users/cuiyaning/data/uni_train_admet_pk/pair_data.json'
task_stats: '/vepfs/fs_users/cuiyaning/data/uni_train_admet_pk/task_stats.json'
task_vocab: '/vepfs/fs_users/cuiyaning/data/uni_train_admet_pk/admet_data_task_vocab.json'
admet_data_path: '/vepfs/fs_users/cuiyaning/data/uni_train_admet_pk/admet_data.json'
admet_test_data_path: '/vepfs/fs_users/cuiyaning/data/uni_train_admet_pk/admet_data_test.json'
